@startuml

!theme vibrant

component "citrusframework/citrus" as citrus #FFCC00
component producer #005B61

component "OpenAPI Specification" as spec #A5C400

citrus -right-> producer
spec <-down- citrus

@enduml