@startuml

!theme vibrant

package "The World" {

    component "citrusframework/citrus" as cit #FFCC00
    component "citrusframework/citrus-simulator" as sim #FFCC00

    cit ..> sim

    package "PostFinance" {
        component "pf/citrus" as pfta #A5C400
        component "pf/citrus-simulator" as pfsim #A5C400

        cit ..> pfta
        pfta ..> pfsim
        sim ..> pfsim
    }
}

@enduml
