@startuml

!theme vibrant

component consumer #FFCC00
component "citrusframework/citrus-simulator" as sim #A5C400

component "<color:#FFFFFF>OpenAPI Specification" as spec #3F3F40

consumer -right-> sim
spec <-down- sim

@enduml