@startuml

!theme vibrant

component "citrusframework/citrus" as citrus #FFCC00
component producer #A5C400

component "<color:#FFFFFF>OpenAPI Specification" as spec #3F3F40

citrus -right-> producer
spec <-down- citrus

@enduml