name: Maven Build

on:
  push:
    branches:
      - '**'
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  application:
    name: 'Banking Application'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          cache: maven
          distribution: 'temurin'
          java-version: 21
      - name: Build Banking Application
        run: ./mvnw -f banking-application/pom.xml -B verify
  client:
    name: 'Banking Client'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          cache: maven
          distribution: 'temurin'
          java-version: 21
      - name: Build Client
        run: ./mvnw -f banking-client/pom.xml -B verify
  simulator:
    name: 'Simulator'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          cache: maven
          distribution: 'temurin'
          java-version: 21
      - name: Build Simulator
        run: ./mvnw -f banking-application-simulator/pom.xml -B verify
